name: Dispatch slash commands

on:
  issue_comment:
    types:
      - created

permissions:
  pull-requests: write
  contents: write

jobs:
  dispatch:
    name: Dispatch command
    runs-on: ubuntu-latest
    environment: pr-merge
    steps:
      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ github.token }}
          commands: |
            merge
          issue-type: pull-request
          permission: write
